version: '3'
services:
        geth:
                image: ethereum/client-go:latest
                entrypoint:
                        - geth
                        - --metrics
                        - --metrics.influxdb
                        - --metrics.influxdb.endpoint=http://dockercomposelightclient_influxdb_1:8086
                        - --metrics.influxdb.database=metrics
                        - --goerli
        influxdb:
                image: influxdb:latest
                expose:
                       - 8086
        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
