version: '3.1'
services:
  lightserver:
    image: ethereum/client-go:latest
    container_name: lightserver
    entrypoint:
      - geth
      - --lightserv=100
      - --rpc
      - --rpcapi=admin,les,web3
      - --rpcaddr=0.0.0.0
      - --goerli
    networks:
      - faucet_network
    ports:
      - "8545:8545"
  faucet:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: offcode/lightfaucet:latest
    container_name: faucet
    depends_on:
      - lightserver
    networks:
      - faucet_network
    ports:
      - "8088:8088"
    entrypoint:
      - faucet
      - --rpcaddr=lightserver
      - --recaptcha.public=/run/secrets/recaptcha_public
      - --recaptcha.secret=/run/secrets/recaptcha_secret
    secrets:
      - recaptcha_public
      - recaptcha_secret
  test_faucet:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    container_name: test_faucet
    depends_on:
      - lightserver
      - faucet
    networks:
      - faucet_network

networks:
  faucet_network:
    driver: overlay

secrets:
  recaptcha_public:
    file: recaptcha_v2_public.txt
  recaptcha_secret:
    file: recaptcha_v2_secret.txt