version: '3'
services:
        geth:
                image: ethereum/client-go:latest
                entrypoint:
                        - geth
                        - --metrics
                        - --metrics.influxdb
                        - --metrics.influxdb.endpoint=http://ze_db:8086
                        - --metrics.influxdb.username=admin
                        - --metrics.influxdb.password=password
                        - --metrics.influxdb.database=metrics
                        - --goerli
        influxdb:
                container_name: ze_db
                image: influxdb:latest
                environment:
                        - INFLUXDB_DB=metrics
                        - INFLUXDB_ADMIN_USERNAME=admin
                        - INFLUXDB_ADMIN_PASSWORD=password
                expose:
                       - 8086
        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
