version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USERNAME=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    expose:
      - 8086
  lightserver:
    image: ethereum/client-go:v1.9.8
    container_name: lightserver
    depends_on:
      - influxdb
    entrypoint:
      - geth
      - --metrics
      - --metrics.influxdb
      - --metrics.influxdb.endpoint=http://influxdb:8086
      - --metrics.influxdb.username=admin
      - --metrics.influxdb.password=password
      - --metrics.influxdb.database=metrics
      - --lightserv=100
      - --rpc
      - --rpcapi=les,admin
      - --rpcaddr=0.0.0.0
      - --goerli
    expose:
      - 8545
    networks:
      - server
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
      - lightserver
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
  faucet:
    image: offcode/lightfaucet:latest
    container_name: faucet
    depends_on:
      - lightserver
    ports:
      - "8088:8088"
    entrypoint:
      - faucet
      - --rpcaddr=lightserver
    networks:
      - server

networks:
  server:
    driver: bridge